- id: door_status_calc_open
  alias: Door Status Calculate Open
  trigger:
    platform: state
    entity_id: binary_sensor.door
    to: 'on'
  condition:
    condition: state
    entity_id: input_select.door_override
    state: real
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.door_result
  - event: VSH_DOOR_PUBLISH_OPEN
- id: door_status_calc_closed
  alias: Door Status Calculate Closed
  trigger:
    platform: state
    entity_id: binary_sensor.door
    to: 'off'
  condition:
    condition: state
    entity_id: input_select.door_override
    state: real
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.door_result
  - event: VSH_DOOR_PUBLISH_CLOSED
- id: door_status_override_closed
  alias: Door Status Override Closed
  trigger:
    platform: state
    entity_id: input_select.door_override
    to: closed
  action:
  - service: homeassistant.turn_off
    entity_id: input_boolean.door_result
  - event: VSH_DOOR_PUBLISH_CLOSED
- id: door_status_override_open
  alias: Door Status Override Open
  trigger:
    platform: state
    entity_id: input_select.door_override
    to: open
  action:
  - service: homeassistant.turn_on
    entity_id: input_boolean.door_result
  - event: VSH_DOOR_PUBLISH_OPEN
- id: door_status_publish_open
  alias: Door Status Publish Open
  trigger:
  - platform: state
    entity_id: input_boolean.door_result
    to: 'on'
  - platform: event
    event_type: VSH_DOOR_PUBLISH_OPEN
  action:
  - service: homeassistant.turn_on
    entity_id: light.door_traffic_light_green
  - service: rest_command.send_door_state_website
  - service: mqtt.publish
    data:
      topic: vsh/door
      payload: open
      retain: true
- id: door_status_publish_closed
  alias: Door Status Publish Closed
  trigger:
  - platform: state
    entity_id: input_boolean.door_result
    to: 'off'
  - platform: event
    event_type: VSH_DOOR_PUBLISH_CLOSED
  action:
  - service: homeassistant.turn_on
    entity_id: light.door_traffic_light_red
  - service: rest_command.send_door_state_website
  - service: mqtt.publish
    data:
      topic: vsh/door
      payload: closed
      retain: true
- id: door_status_publish_periodically
  alias: Door Status Publish Periodically
  trigger:
    platform: time_pattern
    minutes: /5
    seconds: 0
  action:
  - service: rest_command.send_door_state_website
  - service: mqtt.publish
    data:
      topic: vsh/door
      payload_template: '{% if is_state(''input_boolean.door_result'', ''on'') %}open{%
        else %}closed{% endif %}'
      retain: true
- id: ela_doorbell
  alias: Doorbell to ELA
  trigger:
  - entity_id: binary_sensor.doorbell
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: media_player.ela
      media_content_id: http://192.168.9.40/ela/bicycle-dreiklang-1.mp3
      media_content_type: audio/mp3
    service: media_player.play_media
  - delay: 00:00:03
  - data:
      entity_id: media_player.ela
      media_content_id: http://192.168.9.40/ela/tuerklingel_aquarium.mp3
      media_content_type: audio/mp3
    service: media_player.play_media
- id: ela_doorswipe
  alias: Doorswipe to ELA
  trigger:
  - entity_id: binary_sensor.doorswipe
    platform: state
    to: 'on'
  action:
  - data:
      entity_id: media_player.ela
      volume_level: 0.4
    service: media_player.volume_set
  - data:
      entity_id: media_player.ela
      media_content_id: http://192.168.9.40/ela/zen-lo.mp3
      media_content_type: audio/mp3
    service: media_player.play_media
