homeassistant:
  # Name of the location where Home Assistant is running
  name: verschwoerhaus
  # Location required to calculate the time the sun rises and sets
  latitude: 48.39646
  longitude: 9.99041
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 484
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks
     trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.0.0/16
      - 10.72.0.0/21
      - 10.72.72.0/21
      - fd00::/8
        
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

mobile_app:

# Track the sun
sun:

notify:
  - name: briefkasten_bot
    platform: slack
    api_key: !secret briefkasten_slack_bot
    default_channel: "briefkasten-test"

thethingsnetwork:
  app_id: weinhof-briefkasten
  access_key: !secret briefkasten_ttn

sensor:
  - platform: rest
    resource: https://map11.freifunk-ulm.de/data/meshviewer.json
    method: GET
    name: "Freifunk Clients"
    value_template: '{{ value_json.nodes | selectattr("nodeinfo.node_id", "eq", "f6f26d6d4140") | map(attribute="clients") | first }}'
  - platform: thethingsnetwork
    device_id: briefkasten-zda
    values:
      state: ''
      voltage: V
      measure: '/ 1023'
  - platform: rest
    method: GET
    resource: https://sensoren.lorapark.de/api/weather
    name: "Außentemperatur (Lorapark)"
    value_template: "{{ value_json['temp_3'][0]['y'] }}"
    unit_of_measurement: "°C"
  - platform: template
    sensors:
      briefkasten_zda:
        friendly_name: "Briefkasten Digitale Agenda"
        value_template: >-
          {% set expected = -0.038294342664611625*float(states('sensor.aussentemperatur_lorapark'))*float(states('sensor.aussentemperatur_lorapark'))+2.3796209920149796*float(states('sensor.aussentemperatur_lorapark')) +899.8384285406182 %}
          {% if float(states('sensor.briefkasten_zda_measure')) >= expected + 2 %}
            high value
          {% elif float(states('sensor.briefkasten_zda_measure')) <= expected - 2 %}
            low value
          {% else %}
            unsure
          {% endif %}
      briefkasten_zda_akku:
        friendly_name: "Briefkastensensor Akkustand"
        unit_of_measurement: "V"
        value_template: "{{ states('sensor.briefkasten_zda_voltage') }}"
      briefkasten_zda_brightness:
        friendly_name: "Briefkastensensor Helligkeitswert"
        unit_of_measurement: "/ 1023"
        value_template: "{{ states('sensor.briefkasten_zda_measure') }}"


tts:
  - platform: google_translate
    service_name: google_say
    language: 'de'

input_select:
  door_override:
    name: Door status override
    options:
     - real
     - closed
     - open
    initial: real
    icon: mdi:door

input_boolean:
  door_result:
    name: Door status result
    icon: mdi:door

light:
  - platform: mqtt
    name: "Door Traffic Light Green"
    command_topic: "vsh/doorlamp/relay/0/set"
    state_topic: "vsh/doorlamp/relay/0"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Door Traffic Light Red"
    command_topic: "vsh/doorlamp/relay/1/set"
    state_topic: "vsh/doorlamp/relay/1"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Small Fading"
    command_topic: "vsh/sonoffrf/relay/0/set"
    state_topic: "vsh/sonoffrf/relay/0"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Salon Holiday"
    command_topic: "vsh/sonoffrf/relay/7/set"
    state_topic: "vsh/sonoffrf/relay/7"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Corridor Holiday"
    command_topic: "vsh/sonoffrf/relay/6/set"
    state_topic: "vsh/sonoffrf/relay/6"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Couch"
    state_topic: "vsh/couchlamp/relay/0"
    command_topic: "vsh/couchlamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/couchlamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Salon Hex"
    state_topic: "vsh/salon5phex/light/salon_5p_hex/state"
    command_topic: "vsh/salon5phex/light/salon_5p_hex/command"
    availability_topic: "vsh/salon5phex/status"
    schema: json
  - platform: mqtt
    name: "Tree"
    state_topic: "vsh/treelamp/relay/0"
    command_topic: "vsh/treelamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/treelamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Truss"
    state_topic: "vsh/trusslight/relay/0"
    command_topic: "vsh/trusslight/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/trusslight/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Banner"
    state_topic: "vsh/bannerlamp/relay/0"
    command_topic: "vsh/bannerlamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/bannerlamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Rack"
    state_topic: "vsh/racklamp/relay/0"
    command_topic: "vsh/racklamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/racklamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Katze LED-Band"
    state_topic: "vsh/katze_ledband/relay/0"
    command_topic: "vsh/katze_ledband/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/katze_ledband/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Cabinet"
    state_topic: "vsh/cabinet/relay/0"
    command_topic: "vsh/cabinet/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/cabinet/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Wardrobe"
    state_topic: "vsh/wardrobe/relay/0"
    command_topic: "vsh/wardrobe/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/wardrobe/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Aquarium Desk"
    state_topic: "vsh/aquarium_desk/relay/0"
    command_topic: "vsh/aquarium_desk/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/aquarium_desk/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "hallway"
    command_topic: "cmnd/hallway/POWER"
    state_topic: "tele/hallway/STATE"
    state_value_template: "{{value_json.POWER}}"
    availability_topic: "tele/hallway/LWT"
    brightness_command_topic: "cmnd/hallway/Dimmer"
    brightness_state_topic: "tele/hallway/STATE"
    brightness_scale: 100
    on_command_type: "brightness"
    brightness_value_template: "{{value_json.Dimmer}}"
    rgb_command_topic: "cmnd/hallway/Color2"
    rgb_state_topic: "tele/hallway/STATE"
    rgb_value_template: "{{value_json.Color.split(',')[0:3]|join(',')}}"
    effect_command_topic: "cmnd/hallway/Scheme"
    effect_state_topic: "tele/hallway/STATE"
    effect_value_template: "{{value_json.Scheme}}"
    effect_list:
      - 0
      - 1
      - 2
      - 3
      - 4
    payload_on: "ON"
    payload_off: "OFF"
    payload_available: "Online"
    payload_not_available: "Offline"
    qos: 1
    retain: false

switch:
  - platform: mqtt
    name: "Poller"
    command_topic: "vsh/output/poller/set_on_ms"
    state_topic: "vsh/output/poller"
    payload_on: "1500"
    payload_off: "5"
    optimistic: true

rest_command:
  #send_door_state_wordpress:
  #  url: 'https://verschwoerhaus.de/wp-json/open-door/state'
  #  method: 'POST'
  #  content_type: 'application/json'
  #  headers:
  #    Authorization: !secret website_door_auth_header
  #  payload: "{\"open-door\":{\"state\":\"{% if is_state('input_boolean.door_result', 'on') %}open{% else %}closed{% endif %}\"}}"
  send_door_state_spaceapi:
    url: 'https://verschwoerhaus.de/spaceapi/door/'
    method: 'POST'
    content_type: 'application/json'
    headers:
      Authorization: !secret spaceapi_door_auth_header
    payload: "{\"time\":{{ as_timestamp(now()) | int }},\"state\":\"{% if is_state('input_boolean.door_result', 'on') %}opened{% else %}closed{% endif %}\"}"

vacuum:
  - platform: xiaomi_miio
    host: 10.72.72.34
    token: !secret mi_vacuum_rocky_token
    name: rocky
  - platform: xiaomi_miio
    host: 10.72.72.39
    token: !secret mi_vacuum_rocky2_token
    name: rocky2

cast:
  media_player:
    - host: 10.72.72.38
      uuid: "2b35d2ea-17cf-7e25-f356-b2f978b14eca"
    # ^- ela

media_extractor:

system_health:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
