homeassistant:
  # Name of the location where Home Assistant is running
  name: verschwoerhaus
  # Location required to calculate the time the sun rises and sets
  latitude: 48.39646
  longitude: 9.99041
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 484
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Europe/Berlin
  # Customization file
  customize: !include customize.yaml
  auth_providers:
   - type: trusted_networks
     trusted_networks:
      - 127.0.0.1
      - ::1
      - 192.168.0.0/16
      - fd00::/8
        
# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# use the hass.io mosquitto broker
#mqtt:
#  broker: core-mosquitto
#  discovery: true
#  discovery_prefix: homeassistant

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
#conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
#map:

# Track the sun
sun:

# Weather prediction
sensor:
  - platform: rest
    #resource: https://map10.freifunk-ulm.de/data/nodes.json
    resource: https://map11.freifunk-ulm.de/data/meshviewer.json
    method: GET
    name: "Freifunk Clients"
    #value_template: '{{ value_json.nodes | selectattr("nodeinfo.node_id", "eq", "f6f26d6d4140") | map(attribute="statistics") | map(attribute="clients") | first }}'
    value_template: '{{ value_json.nodes | selectattr("nodeinfo.node_id", "eq", "f6f26d6d4140") | map(attribute="clients") | first }}'

#binary_sensor:
#  - platform: mqtt
#    name: "Door"
#    state_topic: "doorsensor/binary_sensor/door/state"
#    payload_off: "0"
#    payload_on: "1"
#    device_class: door
#  - platform: rest
#    resource: http://192.168.9.30
#    method: GET
#    name: Door
#    value_template: '{{ value_json.state.open }}'
#  - name: SonoffRF Status
#    platform: mqtt
#    state_topic: "vsh/sonoffrf/status"
#    device_class: connectivity

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say
    language: 'de'

#device_tracker:
#  - platform: unifi
#    host: "192.168.9.9"
#    username: !secret unifi_username
#    password: !secret unifi_password
#    verify_ssl: False
#    new_device_defaults:
#      track_new_devices: False
#      hide_if_away: True

input_select:
  door_override:
    name: Door status override
    options:
     - real
     - closed
     - open
    initial: real
    icon: mdi:door

input_boolean:
  door_result:
    name: Door status result
    icon: mdi:door

light:
  - platform: mqtt
    name: "Door Traffic Light Green"
    command_topic: "vsh/doorlamp/relay/0/set"
    state_topic: "vsh/doorlamp/relay/0"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Door Traffic Light Red"
    command_topic: "vsh/doorlamp/relay/1/set"
    state_topic: "vsh/doorlamp/relay/1"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Small Fading"
    command_topic: "vsh/sonoffrf/relay/0/set"
    state_topic: "vsh/sonoffrf/relay/0"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Salon Holiday"
    command_topic: "vsh/sonoffrf/relay/7/set"
    state_topic: "vsh/sonoffrf/relay/7"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Corridor Holiday"
    command_topic: "vsh/sonoffrf/relay/6/set"
    state_topic: "vsh/sonoffrf/relay/6"
    payload_off: "0"
    payload_on: "1"
  - platform: mqtt
    name: "Couch"
    state_topic: "vsh/couchlamp/relay/0"
    command_topic: "vsh/couchlamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/couchlamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Salon Hex"
    state_topic: "vsh/salon5phex/light/salon_5p_hex/state"
    command_topic: "vsh/salon5phex/light/salon_5p_hex/command"
    availability_topic: "vsh/salon5phex/status"
    schema: json
  - platform: mqtt
    name: "Tree"
    state_topic: "vsh/treelamp/relay/0"
    command_topic: "vsh/treelamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/treelamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Truss"
    state_topic: "vsh/trusslight/relay/0"
    command_topic: "vsh/trusslight/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/trusslight/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Banner"
    state_topic: "vsh/bannerlamp/relay/0"
    command_topic: "vsh/bannerlamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/bannerlamp/status"
    payload_available: 1
    payload_not_available: 0
  - platform: mqtt
    name: "Rack"
    state_topic: "vsh/racklamp/relay/0"
    command_topic: "vsh/racklamp/relay/0/set"
    payload_on: 1
    payload_off: 0
    availability_topic: "vsh/racklamp/status"
    payload_available: 1
    payload_not_available: 0

switch:
  - platform: mqtt
    name: "Poller"
    command_topic: "vsh/output/poller/set_on_ms"
    state_topic: "vsh/output/poller"
    payload_on: "1500"
    payload_off: "5"
    optimistic: true

rest_command:
  send_door_state_website:
    url: 'https://verschwoerhaus.de/wp-json/open-door/state'
    method: 'POST'
    content_type: 'application/json'
    headers:
      Authorization: !secret website_door_auth_header
    payload: "{\"open-door\":{\"state\":\"{% if is_state('input_boolean.door_result', 'on') %}open{% else %}closed{% endif %}\"}}"

vacuum:
  - platform: xiaomi_miio
    host: 192.168.9.39
    token: !secret mi_vacuum_token

cast:
  media_player:
    - host: 10.72.72.38
    # ^- ela

media_extractor:

system_health:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
