esphomeyaml:
  name: smallpir
  platform: ESP8266
  board: d1_mini

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password

mqtt:
  broker: '192.168.9.43'
  username: ''
  password: ''

# Enable logging
logger:

ota:

binary_sensor:
  - platform: gpio
    pin: D3
    name: "PIR Sensor"
    device_class: motion