esphome:
  name: quality
  platform: ESP8266
  board: nodemcuv2

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  fast_connect: on

mqtt:
  broker: '192.168.9.43'
  username: 'quality'
  password: !secret iot_mqtt_quality_passsword

# Enable logging
logger:

ota:

uart:
  rx_pin: D1
  tx_pin: D2
  baud_rate: 9600

sensor:
  - platform: dht
    pin: D7
    model: DHT22
    temperature:
      name: "Salon Temperature"
    humidity:
      name: "Salon Humidity"
    update_interval: 15s
  - platform: mhz19
    co2:
      name: "Salon CO2"
    temperature:
      name: "Salon MHZ Temperature"
    update_interval: 60s

binary_sensor:
  - platform: gpio
    pin:
      number: D8
      inverted: True
    name: "Salon Side Door"
    device_class: door
