esphome:
  name: salon5phex
  platform: ESP8266
  board: esp01_1m
  board_flash_mode: dout

wifi:
  ssid: !secret iot_wifi_ssid
  password: !secret iot_wifi_password
  fast_connect: on
  use_address: '10.72.72.45'

mqtt:
  broker: '10.72.72.10'
  username: 'hex'
  password: !secret iot_mqtt_salonp5hex_passsword
  topic_prefix: 'vsh/salon5phex'
  discovery: false

# Enable logging
logger:

# Do Not Enable Home Assistant API
#api:

ota:

web_server:
  port: 80

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: "Salon 5P Hex Button"
    discovery: false
    on_press:
      then:
        - switch.toggle:
            id: relay
  - platform: status
    name: "Salon 5P Hex Power Status"
    discovery: false

output:
  - platform: gpio
    pin: 12
    id: 'relay_out'
    
switch:
  - platform: output
    name: "Salon 5P Hex Power"
    output: 'relay_out'
    id: relay
    discovery: false

light:
  - platform: binary
    name: "Salon 5P Hex"
    output: relay_out
    discovery: true